#!/usr/bin/env python3
"""Regenerate `app/lib/core/l10n/strong_bidi_ranges.dart` from the Unicode data
Python ships (ADR-053, issue #137).

WHY A GENERATOR AND NOT A HAND-TYPED TABLE. The tables are 132 + 741 ranges. A
typo in one of them is a silent wrong answer at the seam ADR-033 exists to make
correct, and it would be invisible to review — nobody eyeballs 0x10AEB against
the UCD. So the tables are DERIVED, and this script is how they are re-derived
when Unicode adds a script (it does, roughly annually).

    python3 tool/gen_bidi_rtl_ranges.py            # rewrite the Dart file
    python3 tool/gen_bidi_rtl_ranges.py --check    # exit 1 if it is stale

`--check` runs in CI, so the committed table cannot drift from this script.

⚠️ THE OUTPUT IS PINNED TO A UNICODE VERSION, WHICH IS PINNED TO A PYTHON
VERSION. `unicodedata.unidata_version` is whatever the interpreter shipped with
(3.12 → Unicode 15.0.0). A CI runner on a newer Python emits a different table
and `--check` FAILS — correctly, and confusingly. That failure means "Unicode
moved", and the fix is to run the generator and commit the result, reading the
diff as a changelog. It does not mean the table is corrupt. The emitted header
records the version so the diff says so on its first line.

`strong_bidi_ranges_test.dart` proves the SHAPE of whatever this emits — sorted,
non-overlapping, and the two classes DISJOINT — so a regeneration against a
newer Unicode cannot quietly produce a table the binary search misreads.
"""

from __future__ import annotations

import re
import sys
import unicodedata

OUT = 'app/lib/core/l10n/strong_bidi_ranges.dart'


def ranges(classes: tuple[str, ...]) -> list[tuple[int, int]]:
    """Every code point in the given Bidi_Classes, coalesced into ranges."""
    out: list[list[int]] = []
    for cp in range(0x110000):
        if unicodedata.bidirectional(chr(cp)) not in classes:
            continue
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return [(a, b) for a, b in out]


# `dart format`'s column limit. See `table()`.
LINE_LIMIT = 80


def table(name: str, rs: list[tuple[int, int]], comment: bool) -> str:
    """One `const List<int>` of flat [start, end] pairs.

    ⚠️ THE OUTPUT MUST BE `dart format`-CLEAN, or two CI gates contradict each
    other forever: `dart format --set-exit-if-changed` reformats this file, and
    `--check` then reports the reformatted file as not matching its generator.
    Neither is wrong and no edit satisfies both. So the shape here is dart
    format's OWN choice, reproduced:

      * a pair with a trailing comment stays on one line — the comment prevents
        joining — but only while the line fits in 80 columns, so long Unicode
        names are truncated rather than left for the formatter to split;
      * a pair with NO comment is split one value per line, because that is what
        the formatter does to an uncommented element list.
    """
    lines = []
    for a, b in rs:
        if not comment:
            lines.append(f'  0x{a:04X},')
            lines.append(f'  0x{b:04X},')
            continue
        head = f'  0x{a:04X}, 0x{b:04X}, // '
        name_a = unicodedata.name(chr(a), '?')
        room = LINE_LIMIT - len(head)
        if len(name_a) > room:
            name_a = name_a[: room - 1] + '…'
        lines.append(head + name_a)
    return f'const List<int> {name} = <int>[\n' + '\n'.join(lines) + '\n];\n'


def render(rtl: list[tuple[int, int]], ltr: list[tuple[int, int]]) -> str:
    n_rtl = sum(b - a + 1 for a, b in rtl)
    n_ltr = sum(b - a + 1 for a, b in ltr)
    return f'''// GENERATED by tool/gen_bidi_rtl_ranges.py — do not edit by hand.
// Unicode {unicodedata.unidata_version}.
//
// The two STRONG directional classes of the Unicode Bidirectional Algorithm —
// the property `isolateWithin` needs, and the one `intl` only approximates
// (ADR-053, issue #137):
//
//   strongRtlRanges  Bidi_Class R or AL  {n_rtl:>7} code points in {len(rtl):>3} ranges
//   strongLtrRanges  Bidi_Class L        {n_ltr:>7} code points in {len(ltr):>3} ranges
//
// Everything else is neutral or weak and has NO direction of its own, which is
// exactly the third answer the seam needs and `intl` cannot give. Its two
// classes are approximations in BOTH directions, measured against this same
// Unicode data (intl 0.20.2, the pinned version):
//
//   150     code points intl calls strong-LTR that are strong-RTL  <- #137
//   1,783   strong-RTL code points its RTL class does not reach at all
//   322     code points in its RTL class that are not strong-RTL
//   3,308   code points in its LTR class that are not strong-LTR
//
// intl documents the trade at the constant itself: "simplified for performance
// and small code size." That is a fair trade for `Bidi.startsWithLtr`; it is
// not a basis for a three-way answer, which is why this seam stopped asking.
//
// Flat pairs rather than records: this is scanned per character at a render
// seam, and a flat `List<int>` binary-searches without allocating. The LTR
// table omits per-range names — 741 of them is noise, and the generator is the
// authority anyway.
{table('strongRtlRanges', rtl, comment=True)}
{table('strongLtrRanges', ltr, comment=False)}'''


def committed_unicode_version(text: str) -> str | None:
    """The Unicode version recorded in an already-emitted file's header."""
    for line in text.split('\n', 5):
        m = re.match(r'// Unicode (\S+)\.$', line)
        if m:
            return m.group(1)
    return None


def check(text: str) -> int:
    """Compare the committed file to what THIS interpreter derives.

    The two ways this fails are not the same problem and must not print the same
    sentence. A stale table is someone's mistake; a Unicode bump is news.
    """
    try:
        current = open(OUT).read()
    except FileNotFoundError:
        print(f'{OUT} is missing — run: python3 {sys.argv[0]}', file=sys.stderr)
        return 1
    if current == text:
        print(f'{OUT} is current (Unicode {unicodedata.unidata_version})')
        return 0

    was = committed_unicode_version(current)
    now = unicodedata.unidata_version
    if was is not None and was != now:
        print(
            f'UNICODE MOVED, and this is not a defect.\n'
            f'  committed table : Unicode {was}\n'
            f'  this interpreter: Unicode {now} (Python '
            f'{sys.version.split()[0]})\n'
            f'The table is derived from the interpreter\'s own UCD, so a newer\n'
            f'Python emits a different one. Regenerate and READ THE DIFF AS A\n'
            f'CHANGELOG — added ranges are scripts Unicode {now} assigned a\n'
            f'strong Bidi_Class. A range that DISAPPEARS is worth a second look.\n'
            f'  python3 {sys.argv[0]}',
            file=sys.stderr,
        )
        return 1
    print(
        f'{OUT} does not match its generator, and the Unicode version is\n'
        f'unchanged ({now}) — so this is NOT a Unicode bump. Either the file was\n'
        f'edited by hand (it says not to) or the generator changed without being\n'
        f'run. Regenerate: python3 {sys.argv[0]}',
        file=sys.stderr,
    )
    return 1


def main() -> int:
    text = render(ranges(('R', 'AL')), ranges(('L',)))
    if '--check' in sys.argv:
        return check(text)
    open(OUT, 'w').write(text)
    print(f'wrote {OUT} (Unicode {unicodedata.unidata_version})')
    return 0


if __name__ == '__main__':
    sys.exit(main())
