import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Prod-flavor Firebase options — REAL `hayatiapp-prod` project values,
/// generated by `flutterfire configure` in Session 004 (M1.2, issue #5).
/// iOS block updated Session 037 for the `com.beyondkaira.hayati` bundle-id
/// rename (**ADR-027** — the working-title `com.hayati.app` proved squatted on
/// Apple); a full `flutterfire configure` now targets the new iOS app
/// automatically. The iOS `apiKey` is project-level and unchanged. Session 041
/// re-verified `appId`/`apiKey`/`iosBundleId` against
/// `firebase apps:sdkconfig IOS <appId> --project hayatiapp-prod`: they match
/// the live `Hayati iOS (beyondkaira)` registration exactly (ADR-029 D5).
/// Regenerate with:
///
/// ```sh
/// flutterfire configure --project=hayatiapp-prod \
///   --out=lib/core/firebase/firebase_options_prod.dart \
///   --platforms=android,ios --yes
/// ```
///
/// Committed deliberately — see `firebase_options_dev.dart` for the
/// config-files-are-not-secrets rationale (docs/architecture.md §2).
class ProdFirebaseOptions {
  ProdFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('ProdFirebaseOptions: web is out of MVP scope.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions: unsupported platform $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XoUuJtuadbPHncke5DNRXMxlqD83AHw',
    appId: '1:419979715508:android:132271f59a56b98564c8e1',
    messagingSenderId: '419979715508',
    projectId: 'hayatiapp-prod',
    storageBucket: 'hayatiapp-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KiG1yo-1Y_dIc2j4CwaHbC4B_CUqZe0',
    appId: '1:419979715508:ios:c8c0e5c1fdfadf9d64c8e1',
    messagingSenderId: '419979715508',
    projectId: 'hayatiapp-prod',
    storageBucket: 'hayatiapp-prod.firebasestorage.app',
    iosBundleId: 'com.beyondkaira.hayati',
  );
}
