import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Dev-flavor Firebase options — REAL `hayatiapp-dev` project values,
/// generated by `flutterfire configure` in Session 004 (M1.2, issue #5).
/// Regenerate with:
///
/// ```sh
/// flutterfire configure --project=hayatiapp-dev \
///   --out=lib/core/firebase/firebase_options_dev.dart \
///   --platforms=android,ios --yes
/// ```
///
/// Firebase config files are NOT secrets (API keys are identifiers,
/// restricted per-platform in the Google Cloud console) — committed
/// deliberately (docs/architecture.md §2). Emulator workflows still start
/// firebase-tools with the `demo-hayati` default alias; the Auth/Firestore
/// emulators serve requests addressed to any project id.
class DevFirebaseOptions {
  DevFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DevFirebaseOptions: web is out of MVP scope.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DevFirebaseOptions: unsupported platform $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUf8VA8TmbhwQRW2bpqLWR55UdlbjDOlU',
    appId: '1:870954957461:android:243b773c95ea16cb17f99c',
    messagingSenderId: '870954957461',
    projectId: 'hayatiapp-dev',
    storageBucket: 'hayatiapp-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZNK094Z6Am1RBSa7RhggbqW0c-NMAXac',
    appId: '1:870954957461:ios:9f94680444ff3da217f99c',
    messagingSenderId: '870954957461',
    projectId: 'hayatiapp-dev',
    storageBucket: 'hayatiapp-dev.firebasestorage.app',
    iosBundleId: 'com.hayati.app',
  );
}
